entityName: 'Entrada'
entity: 'MWSimple\Bundle\ForoBundle\Entity\Entrada'
repository: 'MWSimpleForoBundle:Entrada'
index: 'foro_entrada'
new: 'traer_foro'
edit: 'foro_entrada_edit'
show: 'foro_entrada_show'
create: 'mws_entrada_crear'
update: 'foro_entrada_update'
delete: 'foro_entrada_delete'
export: 'foro_entrada_export'
sessionFilter: 'EntradaControllerFilter'
saveAndAdd: false
fieldsindex:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true
    a.titulo:
        label: 'Titulo'
        name: 'Titulo'
        type: 'string'
        export: true
    a.autor:
        label: 'Autor'
        name: 'Autor'
        type: 'MANY_TO_ONE'
    a.grupo:
        label: 'Foro'
        name: 'Grupo'
        type: 'MANY_TO_ONE'
fieldsshow:
    # a.id:
    #     label: 'Id'
    #     name: 'Id'
    #     type: 'integer'
    #     #class: 'col-lg-12'
    #     #closerow: true
    a.titulo:
        label: 'Titulo'
        name: 'Titulo'
        type: 'string'
        class: 'col-lg-8'
        closerow: true
    a.grupo:
        label: 'Foro'
        name: 'Grupo'
        type: 'MANY_TO_ONE'
        class: 'col-lg-6'
        # closerow: true
    a.autor:
        label: 'Autor'
        name: 'Autor'
        type: 'MANY_TO_ONE'
        class: 'col-lg-6'
        closerow: true
    # a.respuestas:
    #     label: 'Respuestas'
    #     name: 'Respuestas'
    #     type: 'ONE_TO_MANY'
    #     #class: 'col-lg-12'
    #     #closerow: true