entityName: 'Grupo'
entity: 'MWSimple\Bundle\ForoBundle\Entity\Grupo'
repository: 'SistemaForoBundle:Grupo'
index: 'foro_grupo'
new: 'foro_grupo_new'
edit: 'foro_grupo_edit'
show: 'foro_grupo_show'
create: 'foro_grupo_create'
update: 'foro_grupo_update'
delete: 'foro_grupo_delete'
export: 'foro_grupo_export'
sessionFilter: 'GrupoControllerFilter'
saveAndAdd: true
fieldsindex:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        #class: 'col-lg-12'
        #closerow: true
    a.miembros:
        label: 'Miembros'
        name: 'Miembros'
        type: 'ONE_TO_MANY'
        #class: 'col-lg-12'
        #closerow: true
    a.entrada:
        label: 'Entrada'
        name: 'Entrada'
        type: 'ONE_TO_MANY'
        #class: 'col-lg-12'
        #closerow: true