entityName: 'Respuesta'
entity: 'MWSimple\Bundle\ForoBundle\Entity\Respuesta'
repository: 'MWSimpleForoBundle:Respuesta'
index: 'foro_respuesta'
new: 'foro_respuesta_new'
edit: 'foro_respuesta_edit'
show: 'foro_respuesta_show'
create: 'foro_respuesta_create'
update: 'foro_respuesta_update'
delete: 'foro_respuesta_delete'
export: 'foro_respuesta_export'
sessionFilter: 'RespuestaControllerFilter'
saveAndAdd: false
fieldsindex:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true
    a.contenido:
        label: 'Contenido'
        name: 'Contenido'
        type: 'text'
        export: true
    a.miembro:
        label: 'Miembro'
        name: 'Miembro'
        type: 'ONE_TO_ONE'
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        #class: 'col-lg-12'
        #closerow: true
    a.contenido:
        label: 'Contenido'
        name: 'Contenido'
        type: 'text'
        #class: 'col-lg-12'
        #closerow: true
    a.miembro:
        label: 'Miembro'
        name: 'Miembro'
        type: 'ONE_TO_ONE'
        #class: 'col-lg-12'
        #closerow: true
    a.entrada:
        label: 'Entrada'
        name: 'Entrada'
        type: 'ONE_TO_MANY'
        #class: 'col-lg-12'
        #closerow: true